Add paged cgm data to nightscout
ps2/rileylink_ios pull request #275
Opened 2016-10-24 22:33 UTC by tmecklem

Summary: This PR adds cgm page uploads to nightscout

Hot on the heels of the most recent release (https://github.com/ps2/rileylink_ios/releases/tag/v0.12.6) which enables fetching recent glucose history on 522 and 722 pumps, this PR enables uploading that cgm data to Nightscout.

Needs discussion/resolution

- [ ] Should we do something like recent-missing-entries in openaps and avoid uploading everything every time?
- [ ] Should using cgm page data be restricted only to x22 model pumps or used also on other pumps to augment the MySentry alert data?
- [ ] Is there a way to detect that a pump isn't using cgm or should we explicitly enable enlite cgm fetching via a UI toggle?

2016-11-01 03:14 UTC, ps2 requested changes

2016-11-01 03:14 UTC, ps2 commented on NightscoutUploadKit/NightscoutUploader.swift
> +    public private(set) var observingGlucoseEventsSince: Date!
I would like to not create any new state in the Uploader. At some point I want to refactor the existing state out. If the state can be kept in device data manager, that would be better.

2016-11-01 03:14 UTC, ps2 commented on NightscoutUploadKit/NightscoutUploader.swift
> +                let entry: [String: Any] = [
We have two methods now creating and serializing SGV records.  Should probably create a new subclass of NightscoutTreatment that knows how to generate a serialized representation, and have both these methods create that.

2016-11-01 03:14 UTC, ps2 commented on RileyLink/DeviceDataManager.swift
> +    static let GlucoseEventsUpdated = Notification.Name(rawValue: "com.rileylink.notification.GlucoseEventsUpdated")
Is this used?

2016-11-01 03:15 UTC, ps2 requested changes
I realize the requested changes are significant. Let me know if you won't be able to work this, and I'll see if I can tackle it at some point.

2016-11-01 03:16 UTC, ps2 requested changes
I realize that the requested changes are significant. Let me know if you won't be able to get to this, and I'll see if I can tackle it.

2016-11-22 02:43 UTC, tmecklem commented
@ps2 the latest code on this branch is running and updating nightscout for my friend's enlite cgm on a 722. I _think_ I addressed the items in your review, but I'm not 100% sure. Please have a look when you get a chance.

I don't have a way to test the changes that impact mysentry glucose readings, so I need help with that. 

Finally, I made a fetch cgm toggle setting for now. I'd like that to be smarter and not require a setting, but I'm going for baby steps of improvement.

2016-11-22 15:02 UTC, ps2 requested changes
Looks great!  Just a formatting request.

2016-11-22 15:02 UTC, ps2 commented on NightscoutUploadKit/NightscoutEntry.swift
> +    let direction : String?
minor nit, but the common style is to not have a space preceding the colon.  There are more of these below.

2016-11-22 15:02 UTC, ps2 commented on NightscoutUploadKit/NightscoutEntry.swift
> +
I would like to eventually make these all structs. But that's probably best left to a refactor.  Not requesting a change here; just a comment.

2016-11-22 15:14 UTC, tmecklem commented on NightscoutUploadKit/NightscoutEntry.swift
> +    let direction : String?
(Personal note for Tim: using this for reference going forward https://github.com/raywenderlich/swift-style-guide#spacing)

2016-11-22 19:27 UTC, ps2 approved these changes

2016-11-22 20:20 UTC, merged