Max settings message clarified
ps2/rileylink_ios pull request #385
Opened 2018-03-28 22:16 UTC by Kdisimone

2018-04-03 04:58 UTC, ps2 requested changes

2018-04-03 04:58 UTC, ps2 commented on MinimedKit/Messages/PumpErrorMessageBody.swift
> +            return NSLocalizedString("Pump setting exceeded; Loop's max basal rate is set higher than the pump's max basal rate", comment: "Pump error code describing max setting exceeded")
This error also occurs when a bolus larger than the pump's max is attempted.   It probably makes sense to put more details into a recovery suggestion like #386

2018-04-03 05:01 UTC, ps2 commented on MinimedKit/Messages/PumpErrorMessageBody.swift
> +            return NSLocalizedString("Pump setting exceeded; Loop's max basal rate is set higher than the pump's max basal rate", comment: "Pump error code describing max setting exceeded")
Also, in this context, it's not necessarily Loop, so the message should be changed to be generic.  Loop specific translations/support can be put into Loop.

2018-04-24 16:50 UTC, Kdisimone commented
Thanks!  I like the recovery suggestion approach.

2018-04-24 16:50 UTC, closed without merging