Add new Read Pulse Log command to Pod Settings
ps2/rileylink_ios pull request #577
Opened 2019-12-29 06:52 UTC by itsmojo

* Display the read pulse log entries with headers
* Change all flash log labels to pulse log instead

2020-01-19 03:22 UTC, ps2 requested changes
Just some organization recommendations and question about some copied code.

2020-01-19 03:22 UTC, ps2 commented on OmniKit/PumpManager/OmnipodPumpManager.swift
> +extension BinaryInteger {
This extension should be fileprivate in the same file responsible for decoding the pulse log (PodInfoPulseLogRecent.swift).

2020-01-19 03:22 UTC, ps2 commented on OmniKit/PumpManager/OmnipodPumpManager.swift
> +    private func pulseLogString(pulseLogEntries: [UInt32], lastPulseNumber: Int) -> String {
This should be in PodInfoPulseLogRecent, since it's a serialization of that object.

2020-01-19 03:22 UTC, ps2 commented on OmniKitTests/PodInfoTests.swift
> +            XCTAssertEqual(0x14602500, decoded.pulseLogEntry[0])
If the same code is decoding entry[0] as entry[n], it's probably sufficient to just test any variations that exercise different aspects of the decoding.

2020-01-19 03:22 UTC, ps2 commented on OmniKit/MessageTransport/MessageBlocks/PodInfoFlashLogRecent.swift
> +public struct PodInfoPulseLogPrevious : PodInfo {
This seems to be largely a copy of the previous decoding. Can they be represented by the same decoding and the same structure?

2020-01-19 19:11 UTC, ps2 commented
What is different between PodInfoPulseLogRecent and PodInfoPulseLogPrevious? Seems like they could be combined into a single struct.

2020-01-19 19:59 UTC, itsmojo commented
The PodInfoPulseLogRecent has information about what the pulse # is for pulse log entries (bytes 3:4 called IIII) while PodInfoPulseLogPrevious has no such information (bytes 3:4 called NNNN is really just redundant length info). This means that to understand what the pulse #'s are for the pulse log entries in a PodInfoPulseLogPrevious return, you need to have the pulse # context which is contained only in the PodInfoPulseLogRecent return. It seems silly that Insulet defined the PodInfoPulseLogPrevious (pod info type 0x51) this way.

2020-01-19 20:46 UTC, ps2 approved these changes

2020-01-23 18:35 UTC, ps2 commented
Already merged; not sure why the PR is still open. Closing.

2020-01-23 18:35 UTC, closed without merging