OrangeLink Patch 3.1 PR to Dev
ps2/rileylink_ios pull request #667
Opened 2021-07-11 13:56 UTC by jlucasvt

PR to with patch files for OrangeLink and OrangeLink Pro.  I received permission from BubbleDev and Vic Wu's team to push the PR to RLKit.   Pete - need some assistance on cleanup and possibly detecting when OL is present to disable the My Sentry instead of commenting it out.

+Adds Battery Level Status Display (%)
+Adds OrangeLink Firmware (FW) and Hardware (HW) Version Listing
+Adds Battery Voltage (volts)
+Adds % Setting and Alert for Low Battery (Off or Set Point)
+Adds Voltage Setting and Alert for Low Voltage Alert (Off or Set Point)
+Adds Toggle to Enable/Disable Connection State 10 Second Blinking LED
+Adds Toggle to Enable/Disable Connection State Disconnect Vibration Alert
+Adds Test Switches to test Yellow and Red LED’s, and the Haptic Motor
+Adds [Find Device] Command (OrangeLink Pro Only)
+Fix for EMALink Communications Error when using Feature Patch
- Disables MySentry Packets to increase OrangeLink battery life with Medtronic x23/x54 pumps

2021-07-14 02:24 UTC, ps2 requested changes
Thanks Jeremy. I haven't gone through the whole thing yet, but yes, it does need to be updated to be more conditional about whether or not the user is using an OL or a RL. If we can get that, I think we can land this; might have a few more changes after a full review.

2021-07-14 02:24 UTC, ps2 commented on MinimedKit/Models/PumpModel.swift
> +        //TODO: disable MySentry when using OL return generation >= 23
This needs to be tackled at a higher level. PumpModels >= 23 should still return that they have MySentry capability, even when using OL, but the MinimedPumpManager could choose not to use it if using OL.

2021-07-14 02:24 UTC, ps2 commented on MinimedKitUI/RileyLinkMinimedDeviceTableViewController.swift
> +    private var fw_hw: String? {
Naming conventions. `fw_hw` -> `firmwareHardware`

2021-07-14 02:24 UTC, ps2 commented on MinimedKitUI/RileyLinkMinimedDeviceTableViewController.swift
> +        updateBatteryLevel()
Some of these should only be done when connected to OL.

2021-07-18 16:15 UTC, ps2 commented
I take a look at updating this patch with the requested changes.

2021-07-18 16:40 UTC, jlucasvt commented
Thank you Pete.

2021-07-18 20:50 UTC, ps2 commented on MinimedKit/Models/PumpModel.swift
> +        //TODO: disable MySentry when using OL return generation >= 23
There is a "Use MySentry" option in pump settings in dev that can be used to enable/disable use of MySentry. The battery tradeoffs are similar on both RL and OL.

2021-07-18 20:54 UTC, ps2 commented on RileyLinkBLEKit/RileyLinkDevice.swift
> +                            let request = UNNotificationRequest.init(identifier: "Orange Low Voltage", content: content, trigger: nil)
Should not be triggering UNNotificationRequests from device code

2021-07-18 20:54 UTC, ps2 commented on RileyLinkBLEKit/RileyLinkDevice.swift
> +                        let request = UNNotificationRequest.init(identifier: "Orange Low Battery", content: content, trigger: nil)
Should not be triggering UNNotificationRequests from device code

2021-07-19 10:03 UTC, bartsopers commented
@ps2 do you have an idea for how to detect that an OL is present? If so, I'd be interested in your solution so we can integrate that in AAPS too.

2021-07-22 15:46 UTC, ps2 commented
> @ps2 do you have an idea for how to detect that an OL is present? If so, I'd be interested in your solution so we can integrate that in AAPS too.

With newer OL firmware, there are OL specific attributes present. For older OL firmware, I think that detecting the secure dfu attribute will be sufficient to distinguish an OL from a RL.

2021-07-22 15:54 UTC, ps2 commented on RileyLinkBLEKit/RileyLinkDevice.swift
> +                            content.title = "Low Voltage"
Strings should be localized.

2021-07-22 15:55 UTC, ps2 commented on RileyLinkBLEKit/RileyLinkDevice.swift
> +                    let value = UserDefaults.standard.integer(forKey: "battery_alert_value")
Alert settings should be stored in PumpManager state.

2021-07-22 15:56 UTC, ps2 commented on RileyLinkBLEKit/PeripheralManager+RileyLink.swift
> +    func findDevices() {
Some of these functions seem to not be supported in early versions of OL firmware. We should hide them if they don't do anything, and people are still using those versions.

2021-07-22 16:17 UTC, ps2 commented
Ongoing work to integrate support into dev is going on here: https://github.com/ps2/rileylink_ios/pull/671

2021-07-22 16:17 UTC, closed without merging

2021-07-24 17:55 UTC, ps2 commented on RileyLinkBLEKit/RileyLinkDevice.swift
> +            self.resetBatteryAlert()
Every single packet is triggering a battery level check.