Fixes to better handle comms optimizations with unreliable comms
ps2/rileylink_ios pull request #669
Opened 2021-07-12 04:38 UTC by itsmojo

+ Add non-persistent var to denote when to skip comms optimizations
+ Set skipNextCommsOptimization on init or for any error or unexpected
  message response to better handle bad comms on restarts and out of range
+ Have updateDeliveryStatus() create an unfinalizedBolus if pod is bolusing
  and PodState doesn't have one to handle both types of status responses
+ Have updateDeliveryStatus() set skipNextCommsOptimization when the pod
  is bolusing or TB is active & it doesn't match the PodState's status
+ Some bolus communication optimization logic improvements
+ Add patchable variable to disable communication optimizations

2021-07-25 12:20 UTC, ps2 requested changes
I'm not sure about accepting the optimization here; having trouble following the logic. The config var needs to go, though. If the optimization should be in the code, it should be in. If not, it should be out. Adding a flag to the code makes the code harder to reason about.

Capturing an active bolus not registered in PodState looks ok, and I can merge that in if you could submit that separately.

2021-07-25 12:20 UTC, ps2 commented on OmniKit/PumpManager/OmnipodPumpManager.swift
> +fileprivate let disableCommsOptimizations = false
Please do not add static debug or config options to the code.

2021-07-26 06:53 UTC, itsmojo commented
Re "I'm not sure about accepting the optimization here; having trouble following the logic". This PR is not an optimization, but an important fix to better handle a number of potential edge cases by avoiding doing the previously merged bolus comms optimization in a number of additional cases that can occur with unreliable communications. Please let me know what logic you are still having trouble following after reading the various comments and logging for the various cases.

2021-07-26 08:35 UTC, itsmojo commented
Closed and replaced by https://github.com/ps2/rileylink_ios/pull/672 to deal with github merge issues. Grrr...

2021-07-26 08:35 UTC, closed without merging